# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{geoip}
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Clifford Heath", "Roland Moriz"]
  s.date = %q{2011-05-06}
  s.default_executable = %q{geoip}
  s.description = %q{GeoIP searches a GeoIP database for a given host or IP address, and
returns information about the country where the IP address is allocated,
and the city, ISP and other information, if you have that database version.}
  s.email = ["clifford.heath@gmail.com", "rmoriz@gmail.com"]
  s.executables = ["geoip"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.rdoc",
    "README.rdoc",
    "Rakefile",
    "bin/geoip",
    "config/website.yml",
    "data/geoip/country_code.yml",
    "data/geoip/country_code3.yml",
    "data/geoip/country_continent.yml",
    "data/geoip/country_name.yml",
    "data/geoip/time_zone.yml",
    "geoip.gemspec",
    "lib/geoip.rb",
    "script/destroy",
    "script/generate",
    "script/txt2html",
    "test/test_geoip.rb",
    "test/test_helper.rb",
    "website/index.txt",
    "website/javascripts/rounded_corners_lite.inc.js",
    "website/stylesheets/screen.css",
    "website/template.rhtml"
  ]
  s.homepage = %q{http://github.com/cjheath/geoip}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{GeoIP searches a GeoIP database for a given host or IP address, and returns information about the country where the IP address is allocated, and the city, ISP and other information, if you have that database version.}
  s.test_files = [
    "test/test_geoip.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

